---
title: "About"
---

* * *

In 1990, I graduated from Harvard University with an A.B. in Psychology. From there I went to Rensselaer Polytechnic Institute, where I earned an M.S. in Industrial and Organizational Psycholopgy in 1992. For three years following my graduation from RPI, I worked at the Stratton VA Medical Center on a research project to test and evaluate a potentially improved mode of health care and social services coordination for older veterans with multiple health problems. When the project was completed, I returned to RPI and earned a Ph.D. in Decision Sciences and Engineering Systems with a focus in Statistics. Since July 2000, I have served in the Department of Mathematical Sciences at Appalachian State University, where I am now a tenured professor.

In my career I have had the opportunity to consult with scholars in many disciplines and investigate an astounding variety of interesting research questions with them. Over time, the method and technology of data exploration and analysis have evolved, and I along with them. Open source technologies like R and GitHub are an exciting revolution in the field that allow for greater control, sharing, and transparency of scientific research and results, data analyses, and educational methodologies. 


* * * 
