---
title: "Advising/AppState"
output: html_document
---

<hr>

## Degree Works & Classes

* [AppalNet Main Page](https://appalnet.appstate.edu/)
* [Degree Works Main Page](https://registrar.appstate.edu/degreeworks)
* [Early Registration Access Page](https://registrar.appstate.edu/students/registration-classes/early-registration-access)
* [Self-Service Direct Link (Banner 9)](https://bannerweb.appstate.edu/)
* [Student Self-Service Guide (Banner 9)](https://confluence.appstate.edu/spaces/ATKB/pages/339509456/Student+Self-Service+Guide)
* [Class Search Direct Link (Banner 9)](https://bannerxe.appstate.edu/StudentRegistrationSsb/ssb/term/termSelection?mode=search)
* [University Exam Schedules](https://registrar.appstate.edu/calendars-schedules/exam-schedule-0)

## Mathematical Sciences

* [Department of Mathematical Sciences](https://mathsci.appstate.edu/)
* [Special Course Offerings](https://mathsci.appstate.edu/nonstandard_courses)
* [Department Honors Program](https://mathsci.appstate.edu/academics/honors-program)
* [Certificate in Sports Analytics](https://mathsci.appstate.edu/academics/sports-analytics-certificate)
* [Minor in Mathematics or Statistics](https://mathsci.appstate.edu/academics/minoring-math-or-statistics)
* [Related: CS Data Science Certificate](https://cs.appstate.edu/data_science/)

## University & College

* [Office of the Registrar](https://registrar.appstate.edu/)
* [College of Arts and Sciences](https://cas.appstate.edu/)
* [College of Arts and Sciences Student Forms](https://cas.appstate.edu/advising/student-forms)
* [Student Conduct and Academic Integrity](https://studentconduct.appstate.edu/)
* [Student Success Services & Support](https://studentsuccess.appstate.edu/)

## Undergraduate Bulletins

* [Undergraduate Bulletin 2025-2026 Main Page](https://bulletin.appstate.edu/index.php?catoid=39)
* [Undergraduate Bulletin 2024-2025 Main Page](https://bulletin.appstate.edu/index.php?catoid=34)
* [Undergraduate Bulletin 2023-2024 Main Page](https://bulletin.appstate.edu/index.php?catoid=30)

## Faculty Resurces

* [Math Sci Faculty Info (restricted access)](https://drive.google.com/drive/folders/0AMSn-D3ZZo8tUk9PVA)
* [Academic Affairs Resources and Forms](https://academicaffairs.appstate.edu/resources-forms)
* [AppState Brand Guides & Resources](https://uc.appstate.edu/brand-guides-resources)

<hr>
