---
title: "Dr. Thomley's Fall 2018 Schedule"
output: 
  html_document:
    toc: true
    toc_float:
      collapsed: false
---

* * *

## Office Hours <i class="fa fa-clock-o"></i>

My office is 228 Walker Hall. Students may schedule an appointment online using [book now](https://thomleyje.youcanbook.me/). Drop-ins during office hours are welcomed and encouraged, but appointments will take precedence.

```{r, echo = FALSE}
library(kableExtra)
df <- data.frame(Time = c("09:00-09:30",
                          "09:30-10:00",
                          "10:00-10:30", 
                          "10:30-11:00", 
                          "11:00-11:30", 
                          "11:30-12:00", 
                          "12:00-12:30", 
                          "12:30-01:00", 
                          "01:00-01:30",
                          "01:30-02:00",
                          "02:00-02:30",
                          "02:30-03:00",
                          "03:00-03:30",
                          "03:30-04:00",
                          "04:00-04:30",
                          "04:30-05:00"), 
                 Monday = c("---",
                            "---",
                            "STT3850-101", 
                            "STT3850-101", 
                            "STT3850-102", 
                            "STT3850-102", 
                            "Office Hour", 
                            "Office Hour", 
                            "Office Hour",
                            "---",
                            "---",
                            "---",
                            "---",
                            "---",
                            "---",
                            "---"), 
                 Tuesday = c("---",
                             "---",
                            "STT3850-101", 
                            "STT3850-101", 
                            "STT3850-102", 
                            "STT3850-102", 
                            "Office Hour", 
                            "Office Hour", 
                            "Office Hour",
                            "---",
                            "---",
                            "---",
                            "---",
                            "STT3530-101",
                            "STT3530-101",
                            "STT3530-101"),  
                 Wednesday = c("---",
                               "---",
                            "STT3850-101", 
                            "STT3850-101", 
                            "STT3850-102", 
                            "STT3850-102", 
                            "Office Hour", 
                            "Office Hour", 
                            "Office Hour",
                            "---",
                            "---",
                            "---",                            
                            "---",
                            "---",
                            "---",
                            "---"), 
                 Thursday = c("---",
                              "---",
                            "STT3850-101", 
                            "STT3850-101", 
                            "STT3850-102", 
                            "STT3850-102", 
                            "Office Hour", 
                            "Office Hour", 
                            "Meeting",
                            "Meeting",
                            "---",
                            "---",
                            "---",
                            "STT3530-101",
                            "STT3530-101",
                            "STT3530-101"), 
                 Friday = c("Scholarship",
                            "Scholarship",
                            "Scholarship", 
                            "Scholarship", 
                            "Scholarship", 
                            "Scholarship", 
                            "Scholarship", 
                            "Scholarship", 
                            "Scholarship",
                            "Scholarship",
                            "Scholarship", 
                            "Scholarship", 
                            "Scholarship", 
                            "Scholarship", 
                            "Scholarship", 
                            "Scholarship"))
knitr::kable(df, format="html", align = c("c","c","c","c","c","c")) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

* * *

```{r include = FALSE}
library(leaflet)
library(dplyr)
```

## Find Walker Hall <i class="fa fa-map-marker"></i>

Use the leaflet map below to find Walker Hall.
 

```{r, echo = FALSE}
leaflet() %>%
  setView(lng=-81.684954, lat=36.216777, zoom = 16) %>% 
  addTiles() %>%
  addMarkers(lng=-81.684954, lat=36.216777, popup="Walker Hall") 
```

* * *

## ASU Dates and Times <i class="fa fa-calendar-check-o"></i>

<ul class="fa-ul">
  <li><i class="fa-li fa fa-calendar"></i>[Academic Calendar](https://registrar.appstate.edu/calendars-schedules/academic-calendar)</li>
  <li><i class="fa-li fa fa-list"></i>[Final Exam Schedule](https://registrar.appstate.edu/calendars-schedules/exam-schedule-0)</li>
  <li><i class="fa-li fa fa-graduation-cap"></i>[Registration and Classes](https://registrar.appstate.edu/students/registration-classes)</li>
</ul>


* * *