---
title: "Dr. Thomley's Fall 2019 Schedule"
output: html_document
---

<hr>

My office is 228 Walker Hall. I am usually on campus Tuesday, Wednesday, and Thursday. Students enrolled in my classes should use their private forums on AsULearn to contact me electronically when needed. I will not answer direct email from current students. Changes to this schedule will be announced to students via Course Announcements on AsULearn.

The number of office hours offered in a given semester is a function of the credit hours of standard classes a professor is teaching. You can book Office Hour appointments in 15-minute increments [HERE](https://calendar.google.com/calendar/selfsched?sstoken=UU0zQUk4blgtNW44fGRlZmF1bHR8Y2EyZDZmYTMxNmZjMWEwMjdiMzE0ZjQ1MmEwNDFjMmE). If you feel like you will need more than 15 minutes, book more than one slot. Drop-ins are also welcome, but scheduled appointments will take priority.

```{r, echo = FALSE, message = FALSE}
library(dplyr)
library(kableExtra)
df <- data.frame(Time = c("10:00-10:30",
                          "10:30-11:00",
                          "11:00-11:30",                          
                          "11:30-12:00",                          
                          "12:00-12:30",                          
                          "12:30-01:00",                          
                          "01:00-01:30",                          
                          "01:30-02:00",                          
                          "02:00-02:30",                          
                          "02:30-03:00",                          
                          "03:00-03:30",                          
                          "03:30-04:00",                          
                          "04:00-04:30",                          
                          "04:30-05:00",                          
                          "05:00-05:30",
                          "05:30-06:00",
                          "06:00-06:30",
                          "06:30-07:00",
                          "07:00-07:30",
                          "07:30-08:00"),
                 Monday = c("Class Prep",
                            "Class Prep",
                            "Class Prep",                          
                            "Class Prep",                          
                            "Class Prep",                          
                            "Class Prep",                          
                            "Class Prep",                          
                            "Class Prep",                          
                            "Class Prep",                          
                            "Class Prep",                          
                            "Class Prep",                          
                            "Class Prep",                          
                            "Class Prep",                          
                            "Class Prep",                          
                            "Class Prep",
                            "Class Prep",
                            " ",
                            " ",
                            " ",
                            " "), 
                 Tuesday = c(" ",
                             " ",
                             " ",                          
                             " ",                          
                             " ",                          
                             " ",                          
                             "Class Prep",                          
                             "Class Prep",                          
                             "STT3850",                          
                             "STT3850",                          
                             "STT3850",                          
                             " ",                          
                             "MAT4510",                          
                             "MAT4510",                          
                             " ",
                             "IRB/Meeting",
                             "IRB/Meeting",
                             "IRB/Meeting",
                             "IRB/Meeting",
                             "IRB/Meeting"),  
                 Wednesday = c(" ",
                               " ",
                               "Class Prep",                          
                               "Office Hours",                          
                               "Office Hours",                          
                               "Office Hours",                          
                               "Office Hours",                          
                               "Class Prep",                          
                               "STT3850",                          
                               "STT3850",                          
                               "Meeting",                          
                               "Meeting",                          
                               "Meeting",                          
                               "Meeting",                          
                               " ",
                               " ",
                               " ",
                               " ",
                               " ",
                               " "),
                 Thursday = c(" ",
                              " ",
                              " ",                          
                              " ",                          
                              " ",                          
                              " ",                          
                              "Class Prep",                          
                              "Class Prep",                          
                              "STT3850",                          
                              "STT3850",                          
                              "STT3850",                          
                              " ",                          
                              " ",                          
                              " ",                          
                              " ",
                              " ",
                              " ",
                              " ",
                              " ",
                              " "),  
                 Friday = c("ARC",
                            "ARC",
                            "ARC",
                            "ARC",
                            "ARC",
                            "ARC",
                            "ARC",                         
                            "ARC",
                            "ARC",
                            "ARC",
                            "ARC",                          
                            "ARC",
                            "ARC",
                            "ARC",
                            "ARC",
                            "ARC",
                            "ARC",
                            "ARC",
                            "ARC",
                            "ARC"))

kable(df, format = "html", escape = FALSE, align = c("c","c","c","c","c","c")) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

ARC is the Academy Research Cluster, an interdisciplinary group of faculty competitively selected to study and evaluate Appalachian's [Academy at Middle Fork](https://middlefork.appstate.edu/) partnership with Winston-Salem/Forsyth County Schools.

<hr>