---
title: "Scholarship"
output: html_document
---

<hr>

## NC State Board of Elections (NCSBE) Post-Election Auditing

I am consulting with the NCSBE on [post-election audits](https://www.ncsbe.gov/about-elections/election-security/post-election-procedures-and-audits), including the current statute-driven audit procerss and a proposal to pilot a [risk-limiting audit](https://www.stat.berkeley.edu/~stark/Preprints/gentle12.pdf). These statistically-driven audits are [becoming more common](https://www.ncsl.org/research/elections-and-campaigns/risk-limiting-audits.aspx) as states seek to address concerns about election security.

## The Academy at Middle Fork Research Cluster and Beyond

I was be part of the Academy Research Cluster (ARC), a competitively-selected interdisciplinary group of faculty that was created with a Special Innovation Grant from the Office of the Chancellor to examine the activities and collaborations of the [Academy at Middle Fork](https://middlefork.appstate.edu/) and its interactions with Appalachian, its community, and its parents. Dr. Mary Searcy and myself have been using Diffusion of Innovation Theory to investigate:

1. What are the aspects of the Academy of Middle Fork-Appalachian State University lab-school  partnership innovation, communication, matters of time, and involved social systems that have been essential to its diffusion process?   
2. What aspects, in hindsight, could have benefited from more intentional planning through the use of Innovation Diffusion Theory?
3. What would an Innovation Diffusion Theory-informed plan for new lab-school partnerships look like as a result of lessons learned at the Academy of Middle Fork?

Following our report to the Academy's advisory board in June 2021 and the cessation of the research cluster as a formal unit, we are continuing our study of the Academy in partnership with Dr. Hannah Reeder, Director of the Academy at Middle Fork.

## Selected Recent Publications (see my [full CV](https://jillthomley.github.io/Thomley-Jill-CV.pdf))

Selbach-Allen, Megan E., Greenwald, Sarah J. Ksir, Amy E., and Thomley, Jill E. (2020). “Raising the Bar with Standards-Based Grading,” _PRIMUS_, 30(8-10), 1110-1126. (special issue)

Henson, Kevin S., Thomley, Jill E., Lowrie, Lynn J., and Walker, Deborah. (2019). “Comparison of Selected Outcomes Associated with Two Post-Operative Analgesia Approaches in the Total Knee Arthroplasty Patient,” _AANA Journal_, 87(1), 51-57. ([web access](https://www.aana.com/publications/aana-journal/all-issues/journal-issue-detail/february-2019))

Thomley, Jill E. (2018). “The History of Statistics: A Discussion-Intensive Seminar on 20th Century Development and Beyond,” In Amy Shell-Gellasch and Dick Jardine (eds.), _The Courses of History: Ideas for Developing a History of Mathematics Course_. Washington, DC: MAA Press. ([web access](https://www.maa.org/press/ebooks/the-courses-of-history))

Thomley, Jill E. (2018). “[Example of a Well-Designed Course in Statistics](http://www.designlearning.org/examples-of-design/examples/),” _Designing Significant Learning Experiences: Course Examples_. 

Santisteban, Maria S., Thomley, Jill E., and Bullard-Dillard, Rebecca. (2017). “S-STEM Scholarship Program at UNC Pembroke: a COMPASS for Science Majors,” _Proceedings of the ASEE Annual Conference & Exposition_ (pp. 5984-6005).  Washington, DC: American Society for Engineering Education.

Hahn, D. Caldwell, Wingfield, John C., Fox, David M., Walker, Brian G., and Thomley, Jill E. (2017). “Maternal Androgens in Avian Brood Parasites and Their Hosts: Responses to Parasitism and Competition?” _General and Comparative Endocrinology_, 240, 143-152.

Greenwald, Sarah J., Leggett, Anne M., and Thomley, Jill E. (2015). “The Association for Women in Mathematics: How and Why It Was Founded, and Why It’s Still Needed in the 21st Century,” _The Mathematical Intelligencer_, 37(3), 11-21.

## The Encyclopedia of Mathematics and Society

Greenwald, S.J. and Thomley, J.E. (Eds). (2011). _The Encyclopedia of Mathematics and Society, Vols. 1-3_. Pasadena, CA: Salem Press. ISBN: 978-1-58765-844-0, e-ISBN: 978-1-58765-848-8

_The goal of The	Encyclopedia	of	Mathematics	and	Society is to weave multilayered connections between society, history, people, applications, and mathematics ... In general, the articles do not teach or present detailed mathematical theory, derivations, and equations ... Instead, we intended them to serve as a foundation and jumping-off point for additional explorations. As mathematics professor and educator Art Johnson has noted in other settings, we hope that this type of contextualization helps people to "see mathematics as a discipline that transcends culture, time, and gender, and as a discipline for everyone, everywhere."_ (Introduction, p. x)

"This enlightening, well-written set, which has no current competitors, is highly recommended for all public and academic libraries. The material offers an entirely new way of looking at things." --- [Library Journal](https://www.libraryjournal.com/) Best Reference, 2011  

Digital access to the _Encyclopedia of Mathematics and Society_ is available through the [ASU Library](https://library.appstate.edu/).

<hr>