---
title: "Teaching"
output: html_document
---

<hr>

## Spring 2023

* STT 1810 Basic Statistics (&times; 2)
* STT 2860 Introduction to Data Management and Visualization

## Fall 2022

* STT 1810 Basic Statistics (&times; 2)
* STT 2860 Introduction to Data Management and Visualization

## Spring 2022

* STT 2860 Introduction to Data Management and Visualization
* STT 3850 Statistical Data Analysis 1

## Fall 2021

* STT 2860 Introduction to Data Management and Visualization
* STT 3850 Statistical Data Analysis 1 (&times; 2)

## Spring 2021

* STT3850 Statistical Data Analysis 1 (&times; 2)

## Fall 2020

* I was on medical leave during Fall 2020.

## Spring 2020

* [STT3500 Intermediate Data Visualization in R](https://github.com/STAT-JET-ASU/IntermediateDataVisR/blob/master/README.md) (&times; 2)
* STT 3500 Statistical Investigation of US Wage Gaps
* STT 3850 Statistical Data Analysis 1
* STT 3520 Instructional Assistant
* MAT 4510 Senior Honors Thesis

## Fall 2019

* STT 2860 Introduction to Data Management and Visualization
* STT 3850 Statistical Data Analysis 1 (&times; 2)
* MAT 4510 Senior Honors Thesis

## Spring 2019

* STT 3530 Data Science 1
* STT 3850 Statistical Data Analysis 1

## Fall 2018

* [STT 3500 Intermediate Data Visualization in R](https://github.com/STAT-JET-ASU/IntermediateDataVisR/blob/master/README.md)
* STT 3530 Data Science 1 
* STT 3850 Statistical Data Analysis 1 (&times; 2)

## Spring 2018

* STT 1810 Basic Statistics
* [STT 3500 Intermediate Statistical Graphing](https://github.com/STAT-JET-ASU/IntermediateDataVisR/blob/master/README.md)
* STT 3530 Data Science 1
* STT 3850 Statistical Data Analysis 1

## Resources

* [GitHub Course Repositories](https://github.com/STAT-JET-ASU)
* [ASU RStudio Server](https://mathr.math.appstate.edu)
* [WileyPLUS](https://education.wiley.com/ngonboard/index.html)
* [StatCrunch](https://www.statcrunch.com/)

<hr>